# name: Deploy

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Use Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18.x'
        
#     - name: Install dependencies
#       run: |
#         npm ci
#         cd client && npm ci
#         cd ../server && npm ci
        
#     - name: Check code formatting
#       run: |
#         npx prettier --check "**/*.{js,jsx,ts,tsx}"
        
#     - name: Build client
#       run: |
#         cd client
#         npm run build
        
#     - name: Run server tests
#       run: |
#         cd server
#         npm test
#       env:
#         CI: true
#         MONGODB_URI: ${{ secrets.MONGODB_URI_TEST }}
  




# # name: Deploy To Render #verify code for this file

# # on:
# #   push:
# #     branches: [main]
# #   pull_request:
# #     branches:
# #       - main

# # jobs:
# #   ci:
# #     name: Deploy To Render
# #     runs-on: ubuntu-latest
# #     steps:
# #       - uses: actions/checkout@v4
# #       - name: Test
# #         run: |
# #           npm install
# #           npm run test

# #       - name: Deploy
# #         # Only run this step if the branch is main
# #         if: github.ref == 'refs/heads/main'
# #         env:
# #           deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
# #         run: |
# #           curl "$deploy_url"
